name             'compute'
maintainer       'Mevan Samaratunga'
maintainer_email 'mevan.samaratunga@fmr.com'
license          'All rights reserved'
description      'Installs/Configures virtual compute infrastructure'
long_description 'Installs/Configures virtual compute infrastructure and provides resources for manipulating virtual machines'
version          '0.1.0'

depends          'sysutils'
depends          'network'
